import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import TrpcProviders from "@/components/providers/TrpcProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` `}
      >
        <SessionProvider>
          <TrpcProviders>
            {children}
          </TrpcProviders>
        </SessionProvider>
      </body>
    </html>
  );
}
